services:
  backend:
    build: ./icake-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - icake-net

  frontend:
    build: ./icake-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    networks:
      - icake-net

  db:
    image: mysql:8
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: icake
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - icake-net
    volumes:
      - db_data:/var/lib/mysql

networks:
  icake-net:

volumes:
  db_data: